ui: tape
browserify:
  - transform:
      name: babelify
  - transform:
      name: bubleify
browsers:
  - name: chrome
    version: latest
  - name: ie
    version: latest
  - name: iphone
    version: latest
  - name: ipad
    version: latest
  - name: safari
    version: latest
  - name: firefox
    version: latest